### ISSUE TITLE
WARNING (aesara.configdefaults) when importing penaltyblog

### ISSUE THREAD

**Issue by nachimbol** [martineastwood/penaltyblog#13]
I'm quite desperate. I'm trying to work with this library, but after installing it, just importing the library launches this error. What can I do? Any guesses?
**This is the code:**

import sys
sys.path.append("../")

import penaltyblog as pb

**This is the error:**

WARNING (aesara.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
WARNING (aesara.configdefaults): g++ not detected!  Aesara will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set Aesara flags cxx to an empty string.
Traceback (most recent call last):
  File "C:\Users\ASUS ROG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aesara\configparser.py", line 237, in fetch_val_for_key
    return self._aesara_cfg.get(section, option)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS ROG\OneDrive - Consejería de Educación, Cultura y Deportes Castilla La-Mancha\Escritorio\Modeling\.conda\Lib\configparser.py", line 
797, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS ROG\OneDrive - Consejería de Educación, Cultura y Deportes Castilla La-Mancha\Escritorio\Modeling\.conda\Lib\configparser.py", line 
1168, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'blas'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ASUS ROG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aesara\configparser.py", line 353, in __get__
    val_str = cls.fetch_val_for_key(self.name, delete_key=delete_key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS ROG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aesara\configparser.py", line 241, in fetch_val_for_key
    raise KeyError(key)
KeyError: 'blas__ldflags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ASUS ROG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\penaltyblog\__init__.py", line 1, in <module>
    from . import (  # noqa
  File "C:\Users\ASUS ROG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\penaltyblog\models\__init__.py", line 1, in <module>
    from .bayesian_bivariate import BayesianBivariateGoalModel  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS ROG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\penaltyblog\models\bayesian_bivariate.py", line 4, in <module>
    import aesara.tensor as tt
  File "C:\Users\ASUS ROG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aesara\__init__.py", line 120, in <module>
    from aesara import scalar, tensor
  File "C:\Users\ASUS ROG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aesara\tensor\__init__.py", line 105, in <module>
    from aesara.tensor import (  # noqa
  File "C:\Users\ASUS ROG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aesara\tensor\blas.py", line 162, in <module>
    from aesara.tensor.blas_headers import blas_header_text, blas_header_version
  File "C:\Users\ASUS ROG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aesara\tensor\blas_headers.py", line 1015, in <module>
    if not config.blas__ldflags:
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS ROG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aesara\configparser.py", line 357, in __get__
    val_str = self.default()
              ^^^^^^^^^^^^^^
  File "C:\Users\ASUS ROG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aesara\link\c\cmodule.py", line 2711, in default_blas_ldflags
    blas_info = np.__config__.get_info("blas_opt")
                ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'numpy.__config__' has no attribute 'get_info'

Just importing penaltyblog is enough to the error to appear, I don't know what to do or how to deal with it.

**Comment by martineastwood** [comment]
Hello - sounds like this is a problem with version mismatches on your system rather than a problem with penaltyblog. pymc has some quite strict dependencies and you need to make sure you have the correct version of numpy so I'd suggest starting off by creating a new virtual environment and installing penaltyblog into that.

**Comment by bytesemantics** [comment]
Had this issue myself today. Resolved by install aesara with latest version. (i.e.  once penaltyblog installed, I manually ran pip install aesara --upgrade)

**Comment by AlessandroMecchia** [comment]
> Had this issue myself today. Resolved by install aesara with latest version. (i.e. once penaltyblog installed, I manually ran pip install aesara --upgrade)

Hi - do you have a requirements.txt? Because I tried updating as you said, but the error is still there.

**Comment by martineastwood** [comment]
I've now bumped the version of pymc that the penaltyblog package depends on so hopefully this will fix your issues with aesara.
